# Generated by Django 5.2.5 on 2025-08-27 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='entityID')),
                ('name', models.CharField(max_length=200, verbose_name='entityName')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='entityType')),
                ('description', models.TextField(blank=True, verbose_name='entityDescribe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdTime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedTime')),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entity',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='relationType')),
                ('description', models.TextField(blank=True, verbose_name='relationDescribe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdTime')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_relations', to='kg_visualize.entity', verbose_name='sourceEntity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_relations', to='kg_visualize.entity', verbose_name='targetEntity')),
            ],
            options={
                'verbose_name': 'entityRelation',
                'verbose_name_plural': 'entityRelation',
                'unique_together': {('source', 'target', 'type')},
            },
        ),
    ]
