# Generated by Django 5.2.5 on 2025-08-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_visualize', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entity',
            name='domain',
            field=models.CharField(default='default', help_text='图谱领域标识', max_length=100, verbose_name='domain'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='domain',
            field=models.CharField(default='default', help_text='图谱领域标识', max_length=100, verbose_name='domain'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('id', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('source', 'target', 'type', 'domain')},
        ),
    ]
